app:
  description: ''
  icon: 🤖
  icon_background: '#FFEAD5'
  mode: advanced-chat
  name: GeoBIM AI Agent
  use_icon_as_answer_icon: false
dependencies:
- current_identifier: null
  type: marketplace
  value:
    marketplace_plugin_unique_identifier: langgenius/openai:0.2.7@9031bbf9b37d9f6341a20c78a8bd18d686afd3ff627545496c3557705419d084
    version: null
kind: app
version: 0.5.0
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: true
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        isInLoop: false
        sourceType: start
        targetType: knowledge-retrieval
      id: 1765032797514-source-1765032814553-target
      source: '1765032797514'
      sourceHandle: source
      target: '1765032814553'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: knowledge-retrieval
        targetType: llm
      id: 1765032814553-source-llm-target
      source: '1765032814553'
      sourceHandle: source
      target: llm
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInLoop: false
        sourceType: llm
        targetType: answer
      id: llm-source-answer-target
      source: llm
      sourceHandle: source
      target: answer
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        selected: false
        title: User Input
        type: start
        variables: []
      height: 73
      id: '1765032797514'
      position:
        x: 69.66171480502669
        y: 101
      positionAbsolute:
        x: 69.66171480502669
        y: 101
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        context:
          enabled: true
          variable_selector:
          - '1765032814553'
          - result
        memory:
          query_prompt_template: '{{#sys.query#}}


            {{#sys.files#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 10
        model:
          completion_params: {}
          mode: chat
          name: gpt-4.1
          provider: langgenius/openai/openai
        prompt_template:
        - id: 4b1bd29f-cc80-49b6-86ff-f5855e6127c9
          role: system
          text: "You're expert. consdering the below context, answer it. \nContext:\
            \ {{#context#}}"
        selected: false
        title: LLM
        type: llm
        vision:
          enabled: false
      height: 88
      id: llm
      position:
        x: 69.66171480502669
        y: 269.3643180950326
      positionAbsolute:
        x: 69.66171480502669
        y: 269.3643180950326
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        answer: '{{#llm.text#}}'
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 102
      id: answer
      position:
        x: 366
        y: 269.3643180950326
      positionAbsolute:
        x: 366
        y: 269.3643180950326
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    - data:
        dataset_ids:
        - XsEdWw8F5iakMyOdfBufoSelUBhoP6b9+8aJZAIrnh29ESU0unVteenDvQZTZjwp
        metadata_filtering_mode: automatic
        metadata_model_config:
          completion_params:
            temperature: 0.7
          mode: chat
          name: gpt-5
          provider: langgenius/openai/openai
        multiple_retrieval_config:
          reranking_enable: false
          reranking_mode: weighted_score
          top_k: 4
          weights:
            keyword_setting:
              keyword_weight: 0.3
            vector_setting:
              embedding_model_name: text-embedding-3-small
              embedding_provider_name: langgenius/openai/openai
              vector_weight: 0.7
            weight_type: customized
        query_variable_selector:
        - sys
        - query
        retrieval_mode: multiple
        selected: false
        title: Knowledge Retrieval
        type: knowledge-retrieval
      height: 90
      id: '1765032814553'
      position:
        x: 366
        y: 122
      positionAbsolute:
        x: 366
        y: 122
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 242
    viewport:
      x: 117.62427408145265
      y: 195.0419377040388
      zoom: 0.8705505632961241
  rag_pipeline_variables: []
